bug fixes

diff --git a/trafikito-agent b/trafikito-agent
--- a/trafikito-agent
+++ b/trafikito-agent
@@ -28,34 +28,138 @@
 
 # SYNOPSIS: The trafikito agent
 
+export DEBUG=1
+
+export PATH=/usr/sbin:/usr/bin:/sbin:/bin
 export AGENT_VERSION=10   # TODO
 
 BASEDIR="${0%/*}"
 BASEDIR=tmp/trafikito  # TODO
 INTERVAL=60   # run every minute
 
-# run without $PATH
-#unset PATH
-
-# source config to get time constraints
+# source configuration
 . $BASEDIR/etc/trafikito.cfg || exit 1
+. $BASEDIR/lib/set_os.sh  # TODO
+# and available commands
+. $BASEDIR/lib/available_commands.sh || exit 1 # TODO this is dangerous!
 
-DOSTART=3     # TODO override minute in hour (0..59) at which agent should run to prevent server overload
+###################################################
+# functions to handle logs instead of using syslog
+###################################################
+export LOGFILE=$BASEDIR/var/log
+
+log() {
+    echo "`date +'%x %X'` $*" >>$LOGFILE
+    test -z "DEBUG" || echo "`date +'%x %X'` $*"
+}
+
+debug() {
+    if [ "$DEBUG" ]; then
+        log $*
+    fi
+}
+
+##########################################################
+# function to get the commands to execute from the server
+##########################################################
+fn_set_commands_to_run() {
+    commands_to_run=`curl -s -X POST -H "Authorization: $API_KEY" \
+                    --data "serverId=$SERVER_ID&agentVersion=$AGENT_VERSION&os=os&osCodename=os_codename&osRelease=os_release&centosFlavor=centos_flavor" \
+                    "$URL_GET_CONFIG" --retry 3 --retry-delay 1 --max-time 30`
+    echo $commands_to_run
+
+    tmp=`echo $commands_to_run | grep '{"data":null,"error":{"code":"#q2w4544h4asa2gAefg53GHrfd","message":'`
+    if [ -n "$tmp" ]; then
+        ERROR="Error: Do not call more then once per minute. ANOTHER_REQUEST_IN_PROGRESS"
+        return 1
+    fi
+
+    tmp=`echo "$commands_to_run" | grep "\"error\":{\"code\":\"#"`
+    if [ -n "$tmp" ]; then
+        ERROR="Error: Can not get commands to run: $tmp"
+        return 1
+    fi
+        
+    if [ -z "$commands_to_run" ];
+    then
+        ERROR="Error: received empty config from Trafikito.com. Probably a network outage?"
+        return 1
+    fi
+    
+    ERROR=""
+    return 0
+}
+
+###########################################
+# execute all commands received from server
+###########################################
+fn_execute_all_commands() {
+    IFS=","
+    # First in commands list is unique call token
+    first="1"
+    log "commands_to_run: $commands_to_run"
+
+    for cmd in $commands_to_run
+    do
+        if [ "$first" -ne "1" ]; then
+            log "Running: $cmd first: $first"
+            fn_execute_trafikito_cmd "$cmd"
+            log "Running $cmd is done"
+        else
+            call_token="$cmd"
+        fi;
+        first="0"
+    done
+}
+
+##########################
+# execute a single command
+##########################
+fn_execute_trafikito_cmd() {
+    # can execute only commands with trafikito_ in it
+    cmd="$1"
+    echo "COMMAND = $cmd" 
+    if [ -z "$cmd" ]; then
+        # can not execute empty string
+        echo "No command specified for execute_trafikito_cmd. Command: $cmd"
+    elif [ $(echo "$cmd" | grep "trafikito_" | sed "s/[^a-zA-Z_]*//g") = "$cmd" ]; then
+        # can execute, let's do it. Echo commands delimiter:
+        echo "*-*-*-*------------ Trafikito command: $cmd" >> "$TMP_FILE"
+        # $cmd is validated. has trafikito_ prefix and is single word with a-Z and _ characters.
+        cmd="$(eval echo "\$$cmd")"
+        
+        # $cmd command is set by user at available_commands.sh
+        eval "$cmd >> $TMP_FILE 2>&1"
+    else
+        # can not execute command without trafikito_ prefix
+        echo "Can not execute command without trafikito_ prefix. Command: $cmd"
+    fi
+}
+
+##########################################
+# collect available commands into TMP_FILE
+##########################################
+fn_collect_available_commands() {
+    echo "*-*-*-*------------ Available commands:" >> "$TMP_FILE"
+    cat "$BASEDIR/lib/available_commands.sh" | grep -v "#" >> "$TMP_FILE"
+}
+
+##################################################
+# start of main
+##################################################
 
 # calculate time to start
 start=`date +%F`
 h=`date +%H`
 h=`expr $h + 1`
 h=`expr $h % 24`
-NODELAY=`date +%s -d "${start}T$h:$DOSTART"`
-
-# testing
-INTERVAL=5
-NODELAY=`date +%s`
+NODELAY=`date +%s -d "${start}T$h:$START_ON"`
 
 while true; do
     start=`date +%s`
-    if [ $start -lt $NODELAY ]; then # wait 5 seconds to get closer to DOSTART
+    if [ $start -lt $NODELAY ]; then # wait 5 seconds to get closer to STARTON
+        debug "delay 5 seconds"
+        debug "$((NODELAY - start)) seconds to go"
         sleep 5
         start=`date +%s`
     fi
@@ -63,118 +167,20 @@ while true; do
     now=`date +%s`
     sleep=$((INTERVAL-now+start))
     if [ $sleep -gt 0 ]; then
-        echo "Sleep $sleep"
-        #sleep $sleep
+        debug "sleep $sleep"
+        sleep $sleep
     fi
 
-    # source everything else to allow dynamic updates
-    . $BASEDIR/lib/set_commands_to_run.sh || exit 1
-
-    # set commands_to_run E.g.: commands_to_run="63e374bd-92be-4275-a985-ba2b8d2a953d,trafikito_uptime,trafikito_total_ram"
+    # gets commands to run from trafikito
     fn_set_commands_to_run
     if [ ! -z "$ERROR" ]; then
-        echo $ERROR
-        echo "Skipping this run"
+        log $ERROR
+        log "Skipping this run"
         continue
     fi
 
     # create new tmp file
-    >$tmp_file
-
-    # Run commands and send results to tmp file
-    fn_execute_all_commands
-exit 1
-
-    # collect available commands from available_commands.sh
-    fn_collect_available_commands
-
-    # Send outputs to Trafikito API
-    fn_send_output_to_trafikito
-
-    # Clean up tmp file
-    >$tmp_file
-
-done
-
-exit 1
-. "${DIR}/functions/set_os.sh"
-. "${DIR}/functions/set_environment.sh"
-. "${DIR}/functions/execute_trafikito_cmd.sh"
-. "${DIR}/functions/send_output.sh"
-. "${DIR}/functions/set_commands_to_run.sh"
-. "${DIR}/functions/execute_all_commands.sh"
-. "${DIR}/functions/collect_available_commands.sh"
-
-# set agent_version
-# set config_file
-# set lock_file
-# set api_key
-# set server_id
-# set tmp_file
-fn_set_environment
-
-# echo "env set agent_version: $agent_version"
-# echo "env set config_file: $config_file"
-# echo "env set api_key: $api_key"
-# echo "env set server_id: $server_id"
-# echo "env set tmp_file: $tmp_file"
-
-# set os
-# set os_codename (may be empty string)
-# set os_release (may be empty string)
-# set centos_flavor (may be empty string)
-fn_set_os
-
-if [ ! -r "${DIR}/functions/set_os.sh" ]; then
-    echo "Missing agent files. Exiting."
-    exit 1;
-fi;
-if [ ! -r "${DIR}/functions/set_environment.sh" ]; then
-    echo "Missing agent files. Exiting."
-    exit 1;
-fi;
-if [ ! -r "${DIR}/functions/execute_trafikito_cmd.sh" ]; then
-    echo "Missing agent files. Exiting."
-    exit 1;
-fi;
-if [ ! -r "${DIR}/functions/send_output.sh" ]; then
-    echo "Missing agent files. Exiting."
-    exit 1;
-fi;
-if [ ! -r "${DIR}/functions/set_commands_to_run.sh" ]; then
-    echo "Missing agent files. Exiting."
-    exit 1;
-fi;
-if [ ! -r "${DIR}/functions/execute_all_commands.sh" ]; then
-    echo "Missing agent files. Exiting."
-    exit 1;
-fi;
-if [ ! -r "${DIR}/functions/collect_available_commands.sh" ]; then
-    echo "Missing agent files. Exiting."
-    exit 1;
-fi;
-
-
-INTERVAL=60  # run every minute
-
-# Don't run all scripts at same time, add some random delay for 1st call
-sleep "$random_number"
-
-while true; do
-
-    start=`date +%s`
-
-    now=`date +%s`
-    sleep=$((INTERVAL-now+start))
-    if [ $sleep -gt 0 ]; then
-        sleep $sleep
-    fi
-
-    # set commands_to_run E.g.: commands_to_run="63e374bd-92be-4275-a985-ba2b8d2a953d,trafikito_uptime,trafikito_total_ram"
-    fn_set_commands_to_run
-
-    # create new tmp file
-    >$tmp_file
+    >$TMP_FILE
 
     # Run commands and send results to tmp file
     fn_execute_all_commands
@@ -183,9 +189,6 @@ while true; do
     fn_collect_available_commands
 
     # Send outputs to Trafikito API
-    fn_send_output_to_trafikito
-
-    # Clean up tmp file
-    >$tmp_file
-
+    curl -s -X POST -H "Authorization: $API_KEY" -H "Content-Type: multipart/form-data" \
+         -F "output=@$TMP_FILE" "$URL_OUTPUT?callToken=$call_token" --retry 3 --retry-delay 1 --max-time 30
 done
